/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sudoku.comm;

@SuppressWarnings("all")
/** Service des profils */
@org.apache.avro.specific.AvroGenerated
public interface Profiles {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Profiles\",\"namespace\":\"com.sudoku.comm\",\"doc\":\"Service des profils\",\"types\":[],\"messages\":{}}");

  @SuppressWarnings("all")
  /** Service des profils */
  public interface Callback extends Profiles {
    public static final org.apache.avro.Protocol PROTOCOL = com.sudoku.comm.Profiles.PROTOCOL;
  }
}